services:
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=Demo Ecs Sample
      - APP_VERSION=1.0.0
      
